
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-frontiers-s26-12
owner: ucsb-cs156-s26
repo_name: proj-frontiers-s26-12
pull_requests: [{"author":{"id":"U_kgDODqxeNQ","is_bot":false,"login":"MrPau13","name":""},"headRefName":"pm-DefaultBasePermission-addHideButton","number":54,"title":"Pm default base permission add hide button","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-12/pull/54"},{"author":{"id":"U_kgDOC5Z6uQ","is_bot":false,"login":"Deb1tto","name":"Pengyu Chen"},"headRefName":"pc-issue-47-delete-repo-endpoint","number":53,"title":"pc Add DELETE /api/repos endpoint for DeleteRepoJob","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-12/pull/53"},{"author":{"id":"U_kgDODqxeNQ","is_bot":false,"login":"MrPau13","name":""},"headRefName":"pm-issue12-backend","number":50,"title":"Pm issue12 connect download student CSV button to API","url":"https://github.com/ucsb-cs156-s26/proj-frontiers-s26-12/pull/50"}]
